 
# 质量，单位：kg
quad_mass : 1.5
# hov_percent会影响最大推力
hov_percent : 0.47

Limit:
    # 位置比例控制
    pxy_int_max: 5.0 
    pz_int_max: 10.0 

hover_gain:
    # 位置比例控制
    Kp_xy: 2.0 
    Kp_z: 2.0 
    # 速度比例控制
    Kv_xy: 2.0
    Kv_z: 2.0
    # 速度积分控制?
    Kvi_xy: 0.3
    Kvi_z: 0.3
    # 加速度前馈系数
    Ka_xy: 1.0
    Ka_z: 1.0
    tilt_angle_max : 10.0

track_gain:
    # 位置比例控制
    Kp_xy: 2.0
    Kp_z: 2.0
    # 速度比例控制
    Kv_xy: 2.0
    Kv_z: 2.0
    # 速度积分控制?
    Kvi_xy: 0.1
    Kvi_z: 0.1
    # 加速度前馈系数
    Ka_xy: 1.0
    Ka_z: 1.0
    tilt_angle_max : 10.0