## parameter for px4_pos_controller.cpp

## 控制器编号: 0 for 串级PID, 1 for PID, 2 for UDE, 3 for passivity,
controller_type: "ne"
## 起飞高度
Takeoff_height : 1.0
## 降落速度
Land_speed : 0.15
##　上锁高度
Disarm_height : 0.1

disturbance_a_xy : 0.0
disturbance_b_xy : 0.00

disturbance_a_z : 0.0
disturbance_b_z : 0.00
disturbance_T : 1.0

disturbance_start_time : 0.0
disturbance_end_time : 0.0

##　地理围栏
geo_fence:
  x_min: -100.0
  x_max: 100.0
  y_min: -100.0
  y_max: 100.0
  z_min: -0.5
  z_max: 100.0

## 限制参数 
Limit:
  tilt_max: 30.0
  XY_VEL_MAX : 3.0
  Z_VEL_MAX : 2.0
  THR_MIN: 0.1
  THR_MAX: 0.9
  ## 积分饱和值
  THR_INT_MAX: 0.2
  ##  
  pxy_error_max: 10.0
  vxy_error_max: 10.0
  pz_error_max: 10.0
  vz_error_max: 10.0
  pxy_int_max : 10.0
  pz_int_max : 10.0
  int_start_error: 10.0

## 飞机参数
Quad:
  mass: 1.0

# 位置环参数 for ne
Pos_ne:
  Kp_xy : 0.3
  Kp_z : 0.3
  Kd_xy : 1.0
  Kd_z : 1.0
  T_ude_xy : 2.0
  T_ude_z : 2.0
  T_ne : 0.2