plugin_blacklist:
- actuator_control
- adsb
- safety_area
- 3dr_radio
- cam_imu_sync
- distance_sensor
- fake_gps
- gps_rtk
- hil
- home_position
- landing_target
- mocap_pose_estimate
- obstacle_distance
- rc_io
- vfr_hud
- waypoint
- wind_estimation
- px4flow
- companion_process_status
- debug_value
- wheel_odometry
- vibration
- odom
- setpoint_attitude
- setpoint_position
- setpoint_accel
- setpoint_velocity
plugin_whitelist: []
#- 'sys_*'