## parameter for px4_pos_controller.cpp

## 控制器编号: 0 for 串级PID, 1 for PID, 2 for UDE, 3 for passivity, 4 for NE
controller_number: 0
## 起飞高度
Takeoff_height : 0.8
## 降落速度
Land_speed : 0.15
##　上锁高度
Disarm_height : 0.1

##　地理围栏
geo_fence:
  x_min: -100.0
  x_max: 100.0
  y_min: -100.0
  y_max: 100.0
  z_min: -0.5
  z_max: 100.0

## 位置环参数 - cascade pid
## 目前参数为PX4默认参数
Pos_cascade_pid:
  Kp_xy : 0.8
  Kp_z : 0.8
  Kp_vxvy : 0.05
  Kp_vz : 0.05
  Ki_vxvy : 0.02
  Ki_vz : 0.1
  Kd_vxvy : 0.016
  Kd_vz : 0.0
  ##悬停油门，取决于飞机重量
  Hover_throttle : 0.46
  MPC_VELD_LP: 5.0

## 限制参数 
Limit:
  tilt_max: 20.0
  XY_VEL_MAX : 3.0
  Z_VEL_MAX : 2.0
  THR_MIN: 0.1
  THR_MAX: 0.9
  ## 积分饱和值
  THR_INT_MAX: 0.2
  ##  
  pxy_error_max: 10.0
  vxy_error_max: 10.0
  pz_error_max: 10.0
  vz_error_max: 10.0
  pxy_int_max : 10.0
  pz_int_max : 10.0
  int_start_error: 10.0

## 飞机参数
Quad:
  mass: 1.0

# 位置环参数 - normal pid
Pos_pid:
  Kp_xy : 2.5
  Kp_z : 2.0
  Ki_xy : 0.5
  Ki_z : 0.5
  Kd_xy : 3.0
  Kd_z : 3.0
