## parameter for px4_sender.cpp

## 起飞高度,建议设置小一点
## 2020.11.04测试发现飞机起飞有较大超调，未发现原因，但起飞后控制正常
Takeoff_height : 0.5
## 降落速度
Land_speed : 0.2
##　上锁高度
Disarm_height : 0.25
## 降落模式选择
Land_mode : 1

##　地理围栏，根据实际情况设置
geo_fence:
  x_min: -50
  x_max: 50
  y_min: -50
  y_max: 50
  z_min: -0.5
  z_max: 50
